'use strict';

const TelegramBot = require('node-telegram-bot-api');
const logger      = require('../utils/logger');

let _bot = null;

function getBot() {
  if (_bot) return _bot;
  const token = process.env.TELEGRAM_BOT_TOKEN;
  if (!token || token === 'your_bot_token_here') return null;
  _bot = new TelegramBot(token);
  return _bot;
}

/**
 * Formats a weekly report object into a Telegram MarkdownV2 message
 * and sends it to the configured chat.
 *
 * @param {object} report  — output of buildWeeklyReport()
 * @returns {Promise<boolean>}  true on success, false on config/send failure
 */
async function sendWeeklyReport(report) {
  const bot    = getBot();
  const chatId = process.env.TELEGRAM_CHAT_ID;

  if (!bot) {
    logger.warn('Telegram: BOT_TOKEN not configured — skipping report send.');
    return false;
  }
  if (!chatId || chatId === 'your_chat_id_here') {
    logger.warn('Telegram: CHAT_ID not configured — skipping report send.');
    return false;
  }

  const text = formatReport(report);

  try {
    await bot.sendMessage(chatId, text, { parse_mode: 'HTML', disable_web_page_preview: true });
    logger.info('Telegram: Weekly report sent successfully.');
    return true;
  } catch (err) {
    logger.error('Telegram: Failed to send report:', err.message);
    return false;
  }
}

/**
 * Converts the report data object into an HTML-formatted Telegram message.
 * Uses HTML mode (not MarkdownV2) to avoid escaping headaches.
 */
function formatReport(r) {
  const date = new Date().toLocaleDateString('en-US', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric',
  });
  const currency = (n) => `$${Number(n || 0).toFixed(2)}`;
  const num      = (n) => Number(n || 0);

  // Revenue trend indicator
  const revenueEmoji = num(r.invoices.collected_this_week) > 0 ? '📈' : '📊';

  let msg = '';

  // Header
  msg += `📊 <b>Weekly SMM Report</b>\n`;
  msg += `<i>${date}</i>\n`;
  msg += `─────────────────────\n\n`;

  // Clients
  msg += `👥 <b>Clients</b>\n`;
  msg += `  Total Active: <b>${num(r.clients.total)}</b>`;
  if (num(r.clients.new) > 0) msg += `  ┊  New this week: <b>+${r.clients.new}</b>`;
  msg += `\n\n`;

  // Orders
  msg += `🛒 <b>Orders</b>\n`;
  msg += `  New this week: <b>${num(r.orders.newThisWeek)}</b>\n`;
  msg += `  In Progress:   <b>${num(r.orders.in_progress)}</b>\n`;
  msg += `  Completed:     <b>${num(r.orders.completed)}</b>\n`;
  if (num(r.orders.pending) > 0) {
    msg += `  Pending:       <b>${num(r.orders.pending)}</b>\n`;
  }
  msg += `\n`;

  // Revenue
  msg += `${revenueEmoji} <b>Revenue</b>\n`;
  msg += `  Collected this week: <b>${currency(r.invoices.collected_this_week)}</b>\n`;
  msg += `  Outstanding:         <b>${currency(r.invoices.unpaid_total)}</b>`;
  if (num(r.invoices.unpaid_count) > 0) {
    msg += ` (${r.invoices.unpaid_count} invoice${r.invoices.unpaid_count !== 1 ? 's' : ''})`;
  }
  msg += `\n`;
  if (num(r.invoices.overdue_count) > 0) {
    msg += `  ⚠️ Overdue invoices: <b>${r.invoices.overdue_count}</b>\n`;
  }
  msg += `\n`;

  // Tasks
  msg += `✅ <b>Tasks</b>\n`;
  msg += `  Done this week: <b>${num(r.tasks.completed_this_week)}</b>\n`;
  msg += `  Still in progress: <b>${num(r.tasks.in_progress)}</b>\n`;
  msg += `  To Do: <b>${num(r.tasks.todo)}</b>\n`;
  if (num(r.tasks.overdue) > 0) {
    msg += `  ⚠️ Overdue: <b>${r.tasks.overdue}</b>\n`;
  }
  msg += `\n`;

  // Recently completed orders
  if (r.recentCompleted.length > 0) {
    msg += `🎉 <b>Completed This Week</b>\n`;
    r.recentCompleted.forEach(o => {
      msg += `  • ${o.business_name} — ${o.service_name} (${currency(o.total_price)})\n`;
    });
    msg += `\n`;
  }

  // Top clients
  if (r.topClients.length > 0) {
    msg += `🏆 <b>Top Clients</b>\n`;
    r.topClients.forEach((c, i) => {
      const medal = ['🥇','🥈','🥉'][i] || '  •';
      msg += `  ${medal} ${c.business_name} — ${c.order_count} orders · ${currency(c.total_value)}\n`;
    });
    msg += `\n`;
  }

  msg += `─────────────────────\n`;
  msg += `<i>Generated by SMM Dashboard</i>`;

  return msg;
}

module.exports = { sendWeeklyReport, formatReport };